### ISSUE TITLE
copy username and password to the clipboard?

### ISSUE THREAD

**Issue by azinsharaf** [passxyz/KPCLibPy#9]
Hi @shugaoye  After I use CAT on a keepass entry, it shows me: Title, Password and Username. Can I copy username and password to the clipboard?

Thanks, Azin

**Comment by passxyz** [comment]
What environment that you are using? I thought it is quite easy to copy the username and password to the clipboard from a terminal, right? It is part of the functionality of terminal. If you are using Windows, Windows Terminal support this kind copy very well.

**Comment by azinsharaf** [comment]
Hi @passxyz , I am using Git bash for Windows inside of Windows Terminal. Can you please clarify how I can copy the username and password to clipboard so I can paste it to the application I need to login.

![image](https://user-images.githubusercontent.com/10101468/153914129-1f215295-ea53-403c-8aca-e0751943b790.png)
